Add labels for clusterings
aertslab/SCope pull request #402
Opened 2020-11-27 18:35 UTC by KrisDavie

Enable labels when searching for All Clusters.

Use community annotations to determine cluster names in the sidebar and in the labels.
This is not applied to search spaces and search results, but annotations are shown in descriptions there

2020-12-02 13:46 UTC, KrisDavie commented
Example output:

![image](https://user-images.githubusercontent.com/5079892/100880475-14ed1380-34ad-11eb-8db1-6798cc3c3cfb.png)

2020-12-03 09:55 UTC, dweemx approved these changes

2020-12-04 13:57 UTC, KrisDavie commented
Also closes #390

2021-01-15 09:46 UTC, dweemx submitted a review, later dismissed
Nice work! Tested :heavy_check_mark:

2021-01-15 11:24 UTC, MaybeJustJames requested changes
Just a few minor changes then I think we're good

2021-01-15 11:24 UTC, MaybeJustJames commented on opt/scopeserver/dataserver/utils/proto.py
> +def protoize_cell_type_annotation(md, secret: str):
What is `md`, can you make it more descriptive and type annotate it please? Also function docstring (without types)

2021-01-15 11:24 UTC, MaybeJustJames commented on opt/scopeserver/dataserver/utils/proto.py
> +                    for i in votes.keys():
```suggestion
                    for i in votes:
```

2021-01-15 11:24 UTC, MaybeJustJames commented on opt/scopeserver/dataserver/utils/proto.py
> +                            v["voter_hash"] = True if user_hash == v["voter_hash"] else False
```suggestion
                            v["voter_hash"] = user_hash == v["voter_hash"]
```

2021-01-15 11:24 UTC, MaybeJustJames commented on opt/scopeserver/dataserver/utils/proto.py
> +                        validate_hash=True if data_hash == cta["validate_hash"] else False,
```suggestion
                        validate_hash=data_hash == cta["validate_hash"],
```

2021-01-15 11:24 UTC, MaybeJustJames commented on opt/scopeserver/dataserver/utils/proto.py
> +def protoize_cluster_marker_metric(metric, cluster_marker_metrics):
Type annotations and function docstring?

2021-01-15 12:38 UTC, MaybeJustJames approved these changes
Great!

2021-01-15 12:38 UTC, merged