Enable testing functions requiring a loom file
aertslab/SCope pull request #407
Opened 2020-12-10 16:44 UTC by KrisDavie

* Include "test" loom in repo, feature complete
* Enable testing of various loom based functions

2021-01-07 10:46 UTC, dweemx requested changes
Nice ! Just 1 small change requested about naming convention and another whether I'm not too sure of...

2021-01-07 10:46 UTC, dweemx commented on opt/scopeserver/gen_test_loom.py
> +def dfToNamedMatrix(df):
Would be good to follow Python convention:
```suggestion
def df_to_named_matrix(df):
```
The function calls therefore should also be changed

2021-01-07 10:46 UTC, dweemx commented on opt/scopeserver/gen_test_loom.py
> +    metaJson = {
I would also suggest to rename it
```suggestion
    meta_json = {
```

2021-01-07 10:46 UTC, dweemx commented on opt/test/test_loom.py
> +    col_attrs["Embedding"] = Loom.dfToNamedMatrix(main_embedding)
Shouldn't this be imported from `opt/scopeserver/gen_test_loom.py` ? Seems to be like redundant code

2021-01-08 13:16 UTC, MaybeJustJames approved these changes
This is great to have in, we can improve as needed.

2021-01-11 12:24 UTC, KrisDavie commented on opt/test/test_loom.py
> +    col_attrs["Embedding"] = Loom.dfToNamedMatrix(main_embedding)
This actually generates different results but is also a proof of concept for generating data in the test to use in the loom file.

2021-01-12 09:46 UTC, dweemx approved these changes
:+1:

2021-01-12 09:47 UTC, merged