Fastapi organisation template
aertslab/SCope pull request #419
Opened 2021-04-08 22:37 UTC by MaybeJustJames

This introduces no-op functionality into the existing SCope application. No "wiring up" has been done. _All_ data is stored in the database. It is treated as an alternative filesystem so existing Loom handling code will still work minus the file handling complexity. The added advantage is that multiple instances of SCope will run on a single machine.

Users are identified by an integer that the client must store in a Cookie. Projects have 2 alternative identifiers: an integer and a uuid-v4. Both of these are generated on the server. Each project stores its size and creation date so that a cron job can clean up as necessary. This means that clients no longer need to poll the server.

To run the server in _development_ configuration simply run the `./run-dev-env.sh` script. Note that the `--reload` option has been removed because it interacts badly with the legacy server. Until the legacy server is removed you will need to manually kill and restart the development server when you modify the code.

2021-04-16 10:32 UTC, dweemx submitted a review, later dismissed
Great work!
Would be nice to have kinda dev `README.md` to know how to start the server, setup database and migrations.

2021-04-28 11:36 UTC, MaybeJustJames commented
> Great work!
> Would be nice to have kinda dev `README.md`

Added. Also added a Postman collection

2021-04-28 16:22 UTC, dweemx approved these changes

2021-05-21 07:22 UTC, MaybeJustJames commented
I started to change "Project" to "Collection" when I realised that the name "Project" also works just as well for an "ad-hoc" collection of datasets as "Collection" does. It's just the concept that changes, rather than a "Project" being a rigid wall around a set of datasets its just an ad-hoc collection that can be.

2021-05-28 11:43 UTC, KrisDavie requested changes
Other than the above comments, I'm also having issues stopping SCope. After running `run-dev-env.sh.sh`, a keyboard interrupt gives an `Aborted!` message, then a second or so later `Terminating Servers...` from SCope's logging. But the bind server never ends, I have needed to kill it manually before I can restart the server.

As noted on Slack also, h5py was updated when I ran `poetry install`, we need to lock below `3.0.0` as the way we search loom files breaks >=3.0.0.

2021-05-28 14:16 UTC, MaybeJustJames commented on config.json
> +    "dataHashSecret": "0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqr",
Ok I'm fine with this. It will cause a validation error on an empty string so that fits nicely :)

2021-06-24 14:30 UTC, dweemx approved these changes
Would just put a default value for the `created` columns in the database. Other than that I'm OK with the FastAPI organisation template :+1:

2021-06-24 14:30 UTC, dweemx commented on opt/scopeserver/models.py
> +    created = Column(DateTime, nullable=False)
This should be filled automatically with a default value
```suggestion
    created = Column(DateTime, nullable=False, , default=datetime.datetime.utcnow)
```

2021-06-24 14:30 UTC, dweemx commented on opt/scopeserver/models.py
> +    created = Column(DateTime, nullable=False)
This should be filled automatically with a default value
```suggestion
    created = Column(DateTime, nullable=False, , default=datetime.datetime.utcnow)
```

2021-06-24 14:30 UTC, dweemx commented on opt/scopeserver/models.py
> +    created = Column(DateTime, nullable=False)
This should be filled automatically with a default value
```suggestion
    created = Column(DateTime, nullable=False, , default=datetime.datetime.utcnow)
```

2021-06-25 07:31 UTC, merged